### PR TITLE
Example Gradient Horizontal Slider 

### PR DESCRIPTION
**Pull request by ekdysis**
- created example Gradient Horizontal Slider
- Swift 5 conversion on AppDelegate.swift file
- white-space clean-up
- created group folder for project organization to demonstrate Gradient Slider

Let me know your thoughts @superbderrick; wanted to contribute to this in a meaningful way.

### CODE REVIEW

**Comment by superbderrick** [comment]
Hey Alex, 
Thanks for you contribution. :)

I have some questions for you implementation

1. Is it possible to draw for gradient effect with existing features? like drawing marks , selectbarcolor.. something like.. 
it would be great  if it possible :) 

2. I assumed that it might be possible CAGradientLayer and drawRect combination for gradient effect.

Can it be implemented inside a horizontalslider? 

Because the user using the slider should be able to set the value as follows:

- selectedBarGradientpercent
- selectedBarGradientColor
- unselectedBarGradientpercent
- unselectedBarGradientColor

ex:
     var marksArray1 = Array<Float>()
      marksArray1 = [0,10,20,30,40,50,60,70,80,90,100]
      testSlider1 = SummerSlider(frame: testRect1)
      testSlider1.selectedBarColor = UIColor.blue
      testSlider1.unselectedBarColor = UIColor.red

      **testSlider1.selectedBarGradientpercent = 50
      testSlider1.selectedBarGradientColor = UIColor.red
      testSlider1.unselectedBarGradientpercent = 50
      testSlider1.unselectedBarGradientColor = UIColor.red**

   
What do you think ?:)

Thanks in advance

Happy new year mate :)

**Comment by ekdysis** [comment]
@superbderrick Good suggestion; I'll add that to the example portion of the project and follow some of the guidelines you've provided above. 

Thanks a ton for taking time to look at this!

Happy New Year, man! Hope 2020 is treating you well so far! 🎉

**Comment by superbderrick** [comment]
Hey @alex-x-x-x-x ,
Thanks your feedback,  let me know when u ar ready:)
Additionally I pushed swift5 converting changes based on your commit 👍 
It will be finished remaining works like a cocopod and document work by today.
Thanks :)

**Comment by ekdysis** [comment]
@superbderrick Sounds good, I'll push this evening. I'm on EST time so it should be relatively early for you still. 😁

Sorry for the small delay in response! 😬

**Comment by superbderrick** [comment]
No worries , Feel free to do it when you have time ;)

**Comment by ekdysis** [comment]
@superbderrick Hey there! Just checking in! 

Currently working on the above implementation, wanted to know if its okay for me to clean up some of the previous gradient work that was implemented on this branch as well?

**Comment by superbderrick** [comment]
@alex-x-x-x-x Hi, Alex sure go ahead :) thx bro

**Comment by ekdysis** [comment]
@superbderrick getting those fixes in today.
 Let me know your thoughts, will more than likely finish everything today. 🌞

**Comment by ekdysis** [comment]
@superbderrick Looks like I'll need to create a new file for `GradientSummerSlider` as a model to be able to leverage some of the functionality from `SummerSlider` in terms of utilizing `markColor`, `markPositions` since `Slider` helps render most of that functionality.

Let me know if you have some time to debug at some point. I'll be available all tonight and all weekend long!

**Comment by superbderrick** [comment]
@alex-x-x-x-x  thx for contribution , let me see the changes :)

**Comment by superbderrick** [comment]
Hey Mate, Thanks for your contribution 

Keep going implementation for gradient effect :) 

I thought that two scenarios regarding new gradient slider Interface.

First thing is that like GradientSummerSlider new types of slider ,  It also good

the other thing is that using original interface. 
Actually summer slider was developed with Factory pattern interface. 

So, If you use a slider API struct , you can configuration  your slider dynamically when drawing action in  summer slider.swift - u can understand from that file.

like this, 
`  override public func draw(_ rect: CGRect) {
    super.draw(rect)
	
	var sliders = [Slider]()
	
	sliders.append(Slider(iMarkColor: self.markColor, iSelectedBarColor: self.selectedBarColor, iUnSelectedBarColor: self.unselectedBarColor, iMarkWidth: self.markWidth, iMarkPositions: self.markPositions,  iDrawingMode: self.drawingMode, style: SliderStyle.Horizontal))
	
	sliders.append(Slider(iMarkColor: self.markColor, iSelectedBarColor: self.selectedBarColor, iUnSelectedBarColor: self.unselectedBarColor, iMarkWidth: self.markWidth, iMarkPositions: self.markPositions,  iDrawingMode: self.drawingMode, style: SliderStyle.Vertical))
    
    sliders.append(Slider(iMarkColor: self.markColor, iSelectedBarColor: self.selectedBarColor, iUnSelectedBarColor: self.unselectedBarColor, iMarkWidth: self.markWidth, iMarkPositions: self.markPositions,  iDrawingMode: self.drawingMode, style: **SliderStyle.Gradient**))
	
    if(**gradientslider**) { . // for public variable for gradient , if the user setup for gradient...
      let gradientSlider = SliderFactory.getSlider(slider: sliders[0])
    }

I don’t are any interface :) 
Do it the way you want to. :)


Thanks 👍

**Comment by ekdysis** [comment]
Added new feature to allow users to select gradient colors directly from Interface Builder (I think you'll really like this @superbderrick as it adheres to how you intended it to be used) 😎

Thanks for your comment @superbderrick -- will definitely investigate today and see if I can wrap it up as quickly as possible.

**Comment by alex-x-x-x-x** [comment]
Can we create a label for this PR for `In Progress`?, I think I may have figured out the solution for this 😬

**Comment by AgmoDarius** [comment]
Hello, is this good to merge with the main branch?

**Comment by superbderrick** [comment]
Hey @AgmoDarius , I didn't check upper changes yet , Let me check asap 
Thanks
D

**Pull request closed without merging**
